### ISSUE TITLE
time of 11:59 gives bad cron

### ISSUE THREAD

**Issue by rleibman** [theycallmeswift/node-mongodb-s3-backup#17]
I used a time of 11:59 and got:

1 Oct 23:59:17 - [info] MongoDB S3 Backup Successfully scheduled (11 59 * * *)

The cron format is MINUTE HOUR, not HOUR MINUTE. 

If I use instead "cron": "59 11 * * *" I get what I expect (plus it wakes up and actually does my backup)

**Comment by theycallmeswift** [comment]
Cron syntax actually goes from shorter times to longer (seconds -> weeks).  This is the expected behavior.  You can find more details here:

ttps://github.com/ncb000gt/node-cron#cron-ranges

**Comment by rleibman** [comment]
That's precisely the bug I'm reporting. If I set it to "time": "11:59" 
it schedules it for hour=59 time=11, whereas if I set it to "cron": "59 
11 * * *" it sets it for 11:59, which is what I expect.

**Comment by theycallmeswift** [comment]
Fixed in v0.0.8
